"""Canonical v12 sector/archetype identifiers and ingest aliases."""

from __future__ import annotations

from typing import Any


LARGE_SECTOR_IDS = (
    "L1_INDUSTRIALS_INFRA_DEFENSE_GRID",
    "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "L3_BATTERY_EV_GREEN_MOBILITY",
    "L4_MATERIALS_SPREAD_RESOURCE",
    "L5_CONSUMER_BRAND_DISTRIBUTION",
    "L6_FINANCIAL_CAPITAL_RETURN_DIGITAL",
    "L7_BIO_HEALTHCARE_MEDICAL",
    "L8_PLATFORM_CONTENT_SW_SECURITY",
    "L9_CONSTRUCTION_REALESTATE_HOUSING",
    "L10_POLICY_EVENT_CROSS_REDTEAM_MISC",
)

CANONICAL_ARCHETYPE_IDS = (
    "C01_ORDER_BACKLOG_MARGIN_BRIDGE",
    "C02_POWER_GRID_DATACENTER_CAPEX",
    "C03_DEFENSE_EXPORT_FRAMEWORK_BACKLOG",
    "C04_NUCLEAR_POLICY_PROJECT_LEGAL_DELAY",
    "C05_EPC_MEGA_CONTRACT_MARGIN_GAP",
    "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "C07_HBM_EQUIPMENT_ORDER_RELATIVE_STRENGTH",
    "C08_SEMI_TEST_SOCKET_CUSTOMER_QUALITY",
    "C09_ADVANCED_EQUIPMENT_VALUATION_BLOWOFF",
    "C10_MEMORY_RECOVERY_EQUIPMENT_CYCLE",
    "C11_BATTERY_ORDERBOOK_RERATING",
    "C12_BATTERY_CUSTOMER_CONTRACT_CALL_OFF_RISK",
    "C13_BATTERY_JV_UTILIZATION_AMPC_IRA",
    "C14_EV_DEMAND_SLOWDOWN_4B_4C",
    "C15_MATERIAL_SPREAD_SUPERCYCLE",
    "C16_STRATEGIC_RESOURCE_POLICY_SUPPLY",
    "C17_CHEMICAL_COMMODITY_MARGIN_SPREAD",
    "C18_CONSUMER_EXPORT_CHANNEL_REORDER",
    "C19_BRAND_RETAIL_INVENTORY_MARGIN",
    "C20_BEAUTY_FOOD_GLOBAL_DISTRIBUTION",
    "C21_FINANCIAL_ROE_PBR_CAPITAL_RETURN",
    "C22_INSURANCE_RATE_CYCLE_RESERVE",
    "C23_BIO_REGULATORY_APPROVAL_COMMERCIALIZATION",
    "C24_BIO_TRIAL_DATA_EVENT_RISK",
    "C25_MEDICAL_DEVICE_EXPORT_REIMBURSEMENT",
    "C26_PLATFORM_AD_REVENUE_OPERATING_LEVERAGE",
    "C27_CONTENT_IP_GLOBAL_MONETIZATION",
    "C28_SOFTWARE_SECURITY_CONTRACT_RETENTION",
    "C29_MOBILITY_VOLUME_MARGIN_OPERATING_LEVERAGE",
    "C30_CONSTRUCTION_PF_BALANCE_SHEET_BREAK",
    "C31_POLICY_SUBSIDY_LEGISLATION_EVENT",
    "C32_GOVERNANCE_CONTROL_PREMIUM_TENDER_CAP",
    "R13_CROSS_ARCHETYPE_STAGE2_FALSE_POSITIVE_REVIEW",
    "R13_CROSS_ARCHETYPE_4B_4C_REDTEAM",
    "R13_CROSS_ARCHETYPE_ACCOUNTING_TRUST_PRICE_VALIDATION",
    "R13_CROSS_ARCHETYPE_HIGH_MAE_GUARDRAIL",
)

LARGE_SECTOR_ALIASES = {
    "L1_INFRA_DEFENSE_GRID": "L1_INDUSTRIALS_INFRA_DEFENSE_GRID",
    "SEMICONDUCTORS": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "SEMICONDUCTOR": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "AI_SEMICONDUCTOR": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "AI_SEMICONDUCTORS": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "AI_SEMICONDUCTOR_ELECTRONICS": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "AI_SEMICONDUCTOR_ELECTRONICS_MEMORY": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "L3_BATTERY_EV_STORAGE": "L3_BATTERY_EV_GREEN_MOBILITY",
    "L3_BATTERY_EV_MOBILITY": "L3_BATTERY_EV_GREEN_MOBILITY",
    "L5_CONSUMER_BRAND_RETAIL": "L5_CONSUMER_BRAND_DISTRIBUTION",
    "L6_FINANCIALS_CAPITAL_RETURN": "L6_FINANCIAL_CAPITAL_RETURN_DIGITAL",
    "L7_BIO_HEALTHCARE": "L7_BIO_HEALTHCARE_MEDICAL",
    "L7_HEALTHCARE_BIO_MEDICAL": "L7_BIO_HEALTHCARE_MEDICAL",
    "L9_CONSTRUCTION_REAL_ESTATE": "L9_CONSTRUCTION_REALESTATE_HOUSING",
    "L9_CONSTRUCTION_REAL_ESTATE_CREDIT": "L9_CONSTRUCTION_REALESTATE_HOUSING",
    "L9_CONSTRUCTION_REAL_ESTATE_PF_CREDIT": "L9_CONSTRUCTION_REALESTATE_HOUSING",
    "L9_MOBILITY_TRANSPORT_LOGISTICS": "L3_BATTERY_EV_GREEN_MOBILITY",
    "L10_POLICY_SUBSIDY_GOVERNANCE_EVENT": "L10_POLICY_EVENT_CROSS_REDTEAM_MISC",
}

CANONICAL_ARCHETYPE_ALIASES = {
    "C02_POWER_GRID_TRANSFORMER_DATA_CENTER_CAPEX": "C02_POWER_GRID_DATACENTER_CAPEX",
    "C02_POWER_GRID_TRANSFORMER_DATACENTER_CAPEX": "C02_POWER_GRID_DATACENTER_CAPEX",
    "AI_HBM_STRUCTURAL_MEMORY_SUPPLIER": "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "AI_HBM_MEMORY_SUPPLIER": "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "HBM_STRUCTURAL_MEMORY_SUPPLIER": "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "HBM_MEMORY_SUPPLIER": "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "MEMORY_HBM_STRUCTURAL_SUPPLIER": "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "AI_HBM_MEMORY_CUSTOMER_CAPACITY": "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "HBM_MEMORY_CUSTOMER_CAPACITY": "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "AI_MEMORY_HBM_CUSTOMER_CAPACITY": "C06_HBM_MEMORY_CUSTOMER_CAPACITY",
    "HBM_EQUIPMENT_ORDER_RELATIVE_STRENGTH": "C07_HBM_EQUIPMENT_ORDER_RELATIVE_STRENGTH",
    "SEMI_TEST_SOCKET_CUSTOMER_QUALITY": "C08_SEMI_TEST_SOCKET_CUSTOMER_QUALITY",
    "ADVANCED_EQUIPMENT_VALUATION_BLOWOFF": "C09_ADVANCED_EQUIPMENT_VALUATION_BLOWOFF",
    "MEMORY_RECOVERY_EQUIPMENT_CYCLE": "C10_MEMORY_RECOVERY_EQUIPMENT_CYCLE",
}

ARCHETYPE_TO_LARGE_SECTOR = {
    "C01_ORDER_BACKLOG_MARGIN_BRIDGE": "L1_INDUSTRIALS_INFRA_DEFENSE_GRID",
    "C02_POWER_GRID_DATACENTER_CAPEX": "L1_INDUSTRIALS_INFRA_DEFENSE_GRID",
    "C03_DEFENSE_EXPORT_FRAMEWORK_BACKLOG": "L1_INDUSTRIALS_INFRA_DEFENSE_GRID",
    "C04_NUCLEAR_POLICY_PROJECT_LEGAL_DELAY": "L1_INDUSTRIALS_INFRA_DEFENSE_GRID",
    "C05_EPC_MEGA_CONTRACT_MARGIN_GAP": "L1_INDUSTRIALS_INFRA_DEFENSE_GRID",
    "C06_HBM_MEMORY_CUSTOMER_CAPACITY": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "C07_HBM_EQUIPMENT_ORDER_RELATIVE_STRENGTH": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "C08_SEMI_TEST_SOCKET_CUSTOMER_QUALITY": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "C09_ADVANCED_EQUIPMENT_VALUATION_BLOWOFF": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "C10_MEMORY_RECOVERY_EQUIPMENT_CYCLE": "L2_AI_SEMICONDUCTOR_ELECTRONICS",
    "C11_BATTERY_ORDERBOOK_RERATING": "L3_BATTERY_EV_GREEN_MOBILITY",
    "C12_BATTERY_CUSTOMER_CONTRACT_CALL_OFF_RISK": "L3_BATTERY_EV_GREEN_MOBILITY",
    "C13_BATTERY_JV_UTILIZATION_AMPC_IRA": "L3_BATTERY_EV_GREEN_MOBILITY",
    "C14_EV_DEMAND_SLOWDOWN_4B_4C": "L3_BATTERY_EV_GREEN_MOBILITY",
    "C15_MATERIAL_SPREAD_SUPERCYCLE": "L4_MATERIALS_SPREAD_RESOURCE",
    "C16_STRATEGIC_RESOURCE_POLICY_SUPPLY": "L4_MATERIALS_SPREAD_RESOURCE",
    "C17_CHEMICAL_COMMODITY_MARGIN_SPREAD": "L4_MATERIALS_SPREAD_RESOURCE",
    "C18_CONSUMER_EXPORT_CHANNEL_REORDER": "L5_CONSUMER_BRAND_DISTRIBUTION",
    "C19_BRAND_RETAIL_INVENTORY_MARGIN": "L5_CONSUMER_BRAND_DISTRIBUTION",
    "C20_BEAUTY_FOOD_GLOBAL_DISTRIBUTION": "L5_CONSUMER_BRAND_DISTRIBUTION",
    "C21_FINANCIAL_ROE_PBR_CAPITAL_RETURN": "L6_FINANCIAL_CAPITAL_RETURN_DIGITAL",
    "C22_INSURANCE_RATE_CYCLE_RESERVE": "L6_FINANCIAL_CAPITAL_RETURN_DIGITAL",
    "C23_BIO_REGULATORY_APPROVAL_COMMERCIALIZATION": "L7_BIO_HEALTHCARE_MEDICAL",
    "C24_BIO_TRIAL_DATA_EVENT_RISK": "L7_BIO_HEALTHCARE_MEDICAL",
    "C25_MEDICAL_DEVICE_EXPORT_REIMBURSEMENT": "L7_BIO_HEALTHCARE_MEDICAL",
    "C26_PLATFORM_AD_REVENUE_OPERATING_LEVERAGE": "L8_PLATFORM_CONTENT_SW_SECURITY",
    "C27_CONTENT_IP_GLOBAL_MONETIZATION": "L8_PLATFORM_CONTENT_SW_SECURITY",
    "C28_SOFTWARE_SECURITY_CONTRACT_RETENTION": "L8_PLATFORM_CONTENT_SW_SECURITY",
    "C29_MOBILITY_VOLUME_MARGIN_OPERATING_LEVERAGE": "L3_BATTERY_EV_GREEN_MOBILITY",
    "C30_CONSTRUCTION_PF_BALANCE_SHEET_BREAK": "L9_CONSTRUCTION_REALESTATE_HOUSING",
    "C31_POLICY_SUBSIDY_LEGISLATION_EVENT": "L10_POLICY_EVENT_CROSS_REDTEAM_MISC",
    "C32_GOVERNANCE_CONTROL_PREMIUM_TENDER_CAP": "L10_POLICY_EVENT_CROSS_REDTEAM_MISC",
    "R13_CROSS_ARCHETYPE_STAGE2_FALSE_POSITIVE_REVIEW": "L10_POLICY_EVENT_CROSS_REDTEAM_MISC",
    "R13_CROSS_ARCHETYPE_4B_4C_REDTEAM": "L10_POLICY_EVENT_CROSS_REDTEAM_MISC",
    "R13_CROSS_ARCHETYPE_ACCOUNTING_TRUST_PRICE_VALIDATION": "L10_POLICY_EVENT_CROSS_REDTEAM_MISC",
    "R13_CROSS_ARCHETYPE_HIGH_MAE_GUARDRAIL": "L10_POLICY_EVENT_CROSS_REDTEAM_MISC",
}

KNOWN_LARGE_SECTOR_KEYS = tuple(sorted(set(LARGE_SECTOR_IDS) | set(LARGE_SECTOR_ALIASES), key=len, reverse=True))
KNOWN_CANONICAL_ARCHETYPE_KEYS = tuple(
    sorted(set(CANONICAL_ARCHETYPE_IDS) | set(CANONICAL_ARCHETYPE_ALIASES), key=len, reverse=True)
)


def _clean_identifier(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip().strip("`").strip().strip('"').strip("'").strip().rstrip(",").strip()
    if not text:
        return None
    return text.upper().replace("-", "_").replace(" ", "_")


def normalise_large_sector_id(value: Any) -> str | None:
    text = _clean_identifier(value)
    if text is None:
        return None
    return LARGE_SECTOR_ALIASES.get(text, text)


def normalise_canonical_archetype_id(value: Any) -> str | None:
    text = _clean_identifier(value)
    if text is None:
        return None
    return CANONICAL_ARCHETYPE_ALIASES.get(text, text)


def large_sector_for_archetype(value: Any) -> str | None:
    canonical = normalise_canonical_archetype_id(value)
    if canonical is None:
        return None
    return ARCHETYPE_TO_LARGE_SECTOR.get(canonical)


__all__ = [
    "CANONICAL_ARCHETYPE_ALIASES",
    "CANONICAL_ARCHETYPE_IDS",
    "ARCHETYPE_TO_LARGE_SECTOR",
    "KNOWN_CANONICAL_ARCHETYPE_KEYS",
    "KNOWN_LARGE_SECTOR_KEYS",
    "LARGE_SECTOR_ALIASES",
    "LARGE_SECTOR_IDS",
    "large_sector_for_archetype",
    "normalise_canonical_archetype_id",
    "normalise_large_sector_id",
]
