"""E2R 2.0 core package."""

from .backtesting import BacktestEngine, Stage3BacktestInput, evaluate_stage3_backtest
from .briefing import (
    MorningBrief,
    MorningBriefInput,
    MorningBriefingGenerator,
    ScheduledEvent,
    generate_morning_briefing,
)
from .connectors import DataConnector, EmptyDataConnector, FallbackDataConnector, MockDataConnector
from .fixtures import FIXTURE_CASES, FixtureCase, FixtureCategory, fixture_cases_by_category
from .models import (
    BacktestResult,
    ConsensusRevision,
    ConsensusSnapshot,
    DisclosureEvent,
    Evidence,
    FinancialActual,
    Instrument,
    Market,
    NewsItem,
    PriceBar,
    RedTeamFinding,
    ResearchReport,
    ScoreSnapshot,
    SectorRegime,
    SourceTier,
    Stage,
    StageSnapshot,
)
from .red_team import (
    HARD_BREAK_SIGNALS,
    SOFT_4B_WEIGHTS,
    THESIS_BREAK_WEIGHTS,
    RedTeamAssessment,
    RedTeamEngine,
    RedTeamRiskLevel,
    RedTeamSignals,
)
from .scoring import (
    CANONICAL_SCORE_COMPONENTS,
    DeterministicScorer,
    ScoreComponentSpec,
    Scorer,
    ScoringPayload,
)
from .staging import (
    ACTIVE_RERATING_STAGES,
    StageClassificationInput,
    StageClassifier,
)

__all__ = [
    "BacktestResult",
    "BacktestEngine",
    "CANONICAL_SCORE_COMPONENTS",
    "ConsensusRevision",
    "ConsensusSnapshot",
    "DataConnector",
    "DeterministicScorer",
    "DisclosureEvent",
    "EmptyDataConnector",
    "Evidence",
    "FIXTURE_CASES",
    "FinancialActual",
    "FallbackDataConnector",
    "FixtureCase",
    "FixtureCategory",
    "HARD_BREAK_SIGNALS",
    "Instrument",
    "Market",
    "MockDataConnector",
    "MorningBrief",
    "MorningBriefInput",
    "MorningBriefingGenerator",
    "NewsItem",
    "PriceBar",
    "RedTeamFinding",
    "RedTeamAssessment",
    "RedTeamEngine",
    "RedTeamRiskLevel",
    "RedTeamSignals",
    "ResearchReport",
    "SOFT_4B_WEIGHTS",
    "ScoreComponentSpec",
    "ScoreSnapshot",
    "Scorer",
    "ScoringPayload",
    "SectorRegime",
    "ScheduledEvent",
    "SourceTier",
    "Stage",
    "Stage3BacktestInput",
    "StageClassificationInput",
    "StageClassifier",
    "StageSnapshot",
    "THESIS_BREAK_WEIGHTS",
    "ACTIVE_RERATING_STAGES",
    "evaluate_stage3_backtest",
    "fixture_cases_by_category",
    "generate_morning_briefing",
]
