"""Canonical open-ended Researcher Mode for E2R v5.

Phase 80 starts this namespace with whole-repository forensics.  Later phases
add the historical atlas, source graph, component researchers, judges, and
deterministic aggregation here so production has one future authority.
"""

from .audits import (
    PHASE80_ARTIFACT_PATHS,
    PHASE84_AUDIT_PATH,
    PHASE84_PASS,
    PHASE85_AUDIT_PATH,
    PHASE85_PASS,
    compile_phase80_forensics,
    compile_phase84_researcher_mode_audit,
    compile_phase85_source_graph_acquisition_audit,
    write_phase80_forensics,
    write_phase84_researcher_mode_audit,
    write_phase85_source_graph_acquisition_audit,
)
from .historical_atlas import (
    ATLAS_OUTPUT_FILES,
    ATLAS_PASS,
    HistoricalJudgmentAtlasResult,
    compile_historical_judgment_atlas,
    compile_historical_judgment_atlas_from_semantic,
    write_historical_judgment_atlas,
)
from .component_anchor_atlas import (
    C06_MANDATORY_ANCHOR_FAMILIES,
    COMPONENT_ANCHOR_PASS,
    compile_component_anchor_atlas,
    compile_component_anchor_atlas_from_files,
    write_component_anchor_atlas,
)
from .schemas import (
    AnchorConfidence,
    BusinessModelMemo,
    CANONICAL_COMPONENT_MAX_POINTS,
    CANONICAL_COMPONENT_ORDER,
    ComponentAnchor,
    ComponentJudgeDecision,
    ComponentJudgeRole,
    ComponentResearchMemo,
    ComponentResearchPlan,
    EvidenceDirection,
    EvidenceFact,
    EvidenceLifecycle,
    FinalComponentDecision,
    HistoricalResearchJudgment,
    HistoricalScoreSchemaType,
    RedTeamMemo,
    SynthesisMemo,
)
from .research_question_seed_catalog import (
    ResearchQuestionSeed,
    ResearchQuestionSeedCatalog,
    load_research_question_seed_catalog,
)
from .question_authority_audit import (
    QUESTION_AUTHORITY_PASS,
    audit_research_question_seed_authority,
)
from .business_model_researcher import (
    BusinessMechanismResearcher,
    BusinessModelResearchResult,
)
from .component_research_planner import (
    COMPONENT_RESEARCHER_ROLE_BY_COMPONENT,
    ComponentResearchPlanner,
)
from .component_researcher import (
    BottleneckPricingResearcher,
    CapitalAllocationResearcher,
    CodexResearcherProvider,
    ComponentResearchResult,
    ComponentResearcher,
    EPSFCFResearcher,
    EarningsVisibilityResearcher,
    InformationConfidenceResearcher,
    MarketExpectationResearcher,
    StructuredResearchProvider,
    ValuationResearcher,
    build_component_researchers,
)
from .red_team_researcher import RedTeamResearchResult, RedTeamResearcher
from .component_judge import (
    AnalystJudge,
    ComponentJudge,
    ComponentJudgeResult,
    SkepticJudge,
    SynthesisJudge,
    SynthesisResult,
)
from .calibration_judge import CalibrationJudge
from .score_aggregator import (
    ComponentAggregationResult,
    DeterministicScoreAggregator,
    DeterministicTotalScore,
    TotalAggregationResult,
)
from .dossier import CanonicalResearchDossierBuilder, ResearcherModeDossier
from .document_ranker import (
    CandidateRankingResult,
    DocumentRelevanceDecision,
    MaterialDocumentRanker,
    ResearcherDocumentRanker,
    SourceCandidateMaterialityDecision,
)
from .evidence_fact_compiler import (
    EvidenceFactCompiler,
    FactCompilationRejection,
    FactCompilationResult,
)
from .source_graph_explorer import (
    ResearcherSourceGraphAcquirer,
    SOURCE_FAMILY_CLASSES,
    SourceGraphAcquisitionConfig,
    SourceGraphAcquisitionMode,
    SourceGraphAcquisitionRun,
    SourceGraphExploration,
    SourceGraphExplorer,
    SourceResearchObjective,
    load_source_graph_checkpoint,
    write_source_graph_acquisition_run,
)
from .source_query_planner import (
    CANONICAL_SOURCE_FAMILIES,
    GeneratedSourceQuery,
    ResearcherSourceQueryPlanner,
    SourceQueryGenerationResult,
)
from .structured_data_researcher import (
    StructuredDataResearcher,
    StructuredMetricRecord,
    StructuredResearchResult,
)
from .research_supervisor import ResearchSupervisor, ResearchSupervisorReview
from .saturation import (
    SATURATION_REVIEW_ROLES,
    SaturationReview,
    SemanticSaturationCertificate,
    SemanticSaturationCertifier,
)

__all__ = [
    "PHASE80_ARTIFACT_PATHS",
    "PHASE84_AUDIT_PATH",
    "PHASE84_PASS",
    "PHASE85_AUDIT_PATH",
    "PHASE85_PASS",
    "compile_phase80_forensics",
    "write_phase80_forensics",
    "ATLAS_OUTPUT_FILES",
    "ATLAS_PASS",
    "AnchorConfidence",
    "AnalystJudge",
    "BusinessMechanismResearcher",
    "BusinessModelMemo",
    "BusinessModelResearchResult",
    "BottleneckPricingResearcher",
    "CANONICAL_COMPONENT_MAX_POINTS",
    "CANONICAL_COMPONENT_ORDER",
    "CANONICAL_SOURCE_FAMILIES",
    "C06_MANDATORY_ANCHOR_FAMILIES",
    "COMPONENT_ANCHOR_PASS",
    "ComponentAnchor",
    "ComponentAggregationResult",
    "ComponentJudge",
    "ComponentJudgeDecision",
    "ComponentJudgeResult",
    "ComponentJudgeRole",
    "ComponentResearchMemo",
    "ComponentResearchPlan",
    "ComponentResearchPlanner",
    "ComponentResearchResult",
    "ComponentResearcher",
    "COMPONENT_RESEARCHER_ROLE_BY_COMPONENT",
    "CanonicalResearchDossierBuilder",
    "CapitalAllocationResearcher",
    "CalibrationJudge",
    "CandidateRankingResult",
    "CodexResearcherProvider",
    "DeterministicScoreAggregator",
    "DeterministicTotalScore",
    "DocumentRelevanceDecision",
    "EPSFCFResearcher",
    "EarningsVisibilityResearcher",
    "EvidenceDirection",
    "EvidenceFact",
    "EvidenceFactCompiler",
    "EvidenceLifecycle",
    "FactCompilationRejection",
    "FactCompilationResult",
    "FinalComponentDecision",
    "HistoricalJudgmentAtlasResult",
    "HistoricalResearchJudgment",
    "HistoricalScoreSchemaType",
    "GeneratedSourceQuery",
    "InformationConfidenceResearcher",
    "MarketExpectationResearcher",
    "MaterialDocumentRanker",
    "QUESTION_AUTHORITY_PASS",
    "ResearchQuestionSeed",
    "ResearchQuestionSeedCatalog",
    "ResearcherDocumentRanker",
    "ResearcherSourceGraphAcquirer",
    "ResearcherSourceQueryPlanner",
    "ResearchSupervisor",
    "ResearchSupervisorReview",
    "ResearcherModeDossier",
    "RedTeamMemo",
    "RedTeamResearchResult",
    "RedTeamResearcher",
    "SATURATION_REVIEW_ROLES",
    "SOURCE_FAMILY_CLASSES",
    "SaturationReview",
    "SemanticSaturationCertificate",
    "SemanticSaturationCertifier",
    "SkepticJudge",
    "SourceGraphExploration",
    "SourceGraphAcquisitionConfig",
    "SourceGraphAcquisitionMode",
    "SourceGraphAcquisitionRun",
    "SourceGraphExplorer",
    "SourceResearchObjective",
    "SourceCandidateMaterialityDecision",
    "SourceQueryGenerationResult",
    "StructuredDataResearcher",
    "StructuredMetricRecord",
    "StructuredResearchProvider",
    "StructuredResearchResult",
    "SynthesisJudge",
    "SynthesisMemo",
    "SynthesisResult",
    "TotalAggregationResult",
    "ValuationResearcher",
    "build_component_researchers",
    "compile_historical_judgment_atlas",
    "compile_historical_judgment_atlas_from_semantic",
    "compile_component_anchor_atlas",
    "compile_phase84_researcher_mode_audit",
    "compile_phase85_source_graph_acquisition_audit",
    "compile_component_anchor_atlas_from_files",
    "write_component_anchor_atlas",
    "audit_research_question_seed_authority",
    "load_research_question_seed_catalog",
    "load_source_graph_checkpoint",
    "write_historical_judgment_atlas",
    "write_phase84_researcher_mode_audit",
    "write_phase85_source_graph_acquisition_audit",
    "write_source_graph_acquisition_run",
]
