"""Build a resumable source graph and open research objectives.

Literal queries are intentionally absent.  They must be generated by the LLM
from the current fact graph and failures in later acquisition phases.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import date
from typing import Any, Mapping, Sequence

from e2r.research_brain.intelligence_schema import stable_intelligence_id

from .schemas import ComponentResearchPlan


SOURCE_FAMILY_CLASSES: Mapping[str, tuple[str, ...]] = {
    "OFFICIAL": (
        "OPENDART",
        "KIND_KRX",
        "ISSUER_EARNINGS_RELEASE",
        "ISSUER_PRESENTATION",
        "ISSUER_NEWSROOM",
        "CUSTOMER_OFFICIAL",
    ),
    "STRUCTURED": (
        "FINANCIAL_STATEMENTS",
        "SEGMENT_DATA",
        "CASH_FLOW",
        "MARKET_CAP_PRICE",
        "CONSENSUS_REVISION",
        "VALUATION_MULTIPLES",
    ),
    "INDEPENDENT": (
        "REUTERS",
        "TRUSTED_BUSINESS_MEDIA",
        "PUBLIC_BROKER_PDF",
        "INDUSTRY_REPORT",
        "NAVER_DISCOVERY",
        "GENERAL_WEB_DISCOVERY",
    ),
}


@dataclass(frozen=True)
class SourceGraphNode:
    node_id: str
    node_type: str
    source_family: str
    target_id: str
    as_of_date: str
    evidence_eligible: bool
    metadata: Mapping[str, Any]

    def to_dict(self) -> Mapping[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class SourceGraphEdge:
    edge_id: str
    from_node_id: str
    to_node_id: str
    relationship: str

    def to_dict(self) -> Mapping[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class SourceResearchObjective:
    objective_id: str
    component_id: str
    research_objective: str
    preferred_source_families: tuple[str, ...]
    counter_or_supersession_required: bool
    literal_query: None = None
    query_must_be_generated_by_llm: bool = True
    budget_required_before_execution: bool = True
    stop_condition: str = "material claim resolved and counter/supersession checked"

    def to_dict(self) -> Mapping[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class SourceGraphExploration:
    nodes: tuple[SourceGraphNode, ...]
    edges: tuple[SourceGraphEdge, ...]
    open_objectives: tuple[SourceResearchObjective, ...]
    covered_source_families: tuple[str, ...]
    checkpoint_required: bool = True
    score_authority: bool = False

    def to_dict(self) -> Mapping[str, Any]:
        return {
            "nodes": [row.to_dict() for row in self.nodes],
            "edges": [row.to_dict() for row in self.edges],
            "open_objectives": [row.to_dict() for row in self.open_objectives],
            "covered_source_families": list(self.covered_source_families),
            "checkpoint_required": self.checkpoint_required,
            "score_authority": self.score_authority,
        }


class SourceGraphExplorer:
    def explore(
        self,
        *,
        target_id: str,
        as_of_date: str,
        documents: Sequence[Mapping[str, Any]],
        research_plans: Sequence[ComponentResearchPlan],
        source_coverage: Sequence[str | Mapping[str, Any]],
    ) -> SourceGraphExploration:
        nodes = []
        edges = []
        cutoff = date.fromisoformat(as_of_date)
        document_node_ids: dict[str, str] = {}
        for row in documents:
            document_id = str(
                row.get("document_id") or row.get("source_id") or ""
            ).strip()
            if not document_id:
                raise ValueError("source graph document_id is required")
            source_family = str(
                row.get("source_family") or row.get("source_tier") or "UNKNOWN"
            ).upper()
            observed = _observed_date(row)
            future = bool(observed and observed > cutoff)
            node_id = stable_intelligence_id(
                "SGNODE",
                {
                    "target_id": target_id,
                    "as_of_date": as_of_date,
                    "document_id": document_id,
                },
            )
            document_node_ids[document_id] = node_id
            nodes.append(
                SourceGraphNode(
                    node_id=node_id,
                    node_type="DOCUMENT",
                    source_family=source_family,
                    target_id=target_id,
                    as_of_date=as_of_date,
                    evidence_eligible=bool(row.get("evidence_eligible", True))
                    and not bool(row.get("snippet_only"))
                    and not future,
                    metadata={
                        key: value
                        for key, value in row.items()
                        if key
                        not in {
                            "full_text",
                            "content",
                            "body",
                            "future_outcome",
                            "reported_stage",
                        }
                    }
                    | ({"future_source_excluded": True} if future else {}),
                )
            )
        for row in documents:
            source_id = str(
                row.get("document_id") or row.get("source_id") or ""
            ).strip()
            for referenced in row.get("referenced_document_ids") or ():
                referenced_id = str(referenced)
                if referenced_id not in document_node_ids:
                    continue
                edge_payload = {
                    "from": document_node_ids[source_id],
                    "to": document_node_ids[referenced_id],
                    "relationship": "REFERENCES",
                }
                edges.append(
                    SourceGraphEdge(
                        edge_id=stable_intelligence_id("SGEDGE", edge_payload),
                        from_node_id=edge_payload["from"],
                        to_node_id=edge_payload["to"],
                        relationship="REFERENCES",
                    )
                )
        covered = _coverage_labels(source_coverage)
        objectives = []
        for plan in research_plans:
            preferred = tuple(
                dict.fromkeys(
                    (*plan.source_route_hints, *plan.counter_route_hints)
                )
            )
            if not preferred:
                # Generic family order, never a target/archetype-specific query.
                preferred = tuple(
                    family
                    for class_name in ("OFFICIAL", "STRUCTURED", "INDEPENDENT")
                    for family in SOURCE_FAMILY_CLASSES[class_name]
                )
            for question in plan.research_questions:
                payload = {
                    "target_id": target_id,
                    "as_of_date": as_of_date,
                    "component_id": plan.component_id,
                    "question": question,
                    "preferred": preferred,
                }
                objectives.append(
                    SourceResearchObjective(
                        objective_id=stable_intelligence_id("SGOBJ", payload),
                        component_id=plan.component_id,
                        research_objective=question,
                        preferred_source_families=preferred,
                        counter_or_supersession_required=True,
                    )
                )
        return SourceGraphExploration(
            nodes=tuple(nodes),
            edges=tuple(edges),
            open_objectives=tuple(objectives),
            covered_source_families=tuple(sorted(covered)),
        )


def _coverage_labels(rows: Sequence[str | Mapping[str, Any]]) -> set[str]:
    labels = set()
    for row in rows:
        if isinstance(row, str):
            value = row
        else:
            value = str(
                row.get("source_family")
                or row.get("route_id")
                or row.get("coverage_id")
                or ""
            )
        if value.strip():
            labels.add(value.strip().upper())
    return labels


def _observed_date(row: Mapping[str, Any]) -> date | None:
    raw = next(
        (
            str(row.get(key)).strip()
            for key in ("published_at", "publication_date", "filed_at", "observed_at")
            if row.get(key)
        ),
        "",
    )
    if not raw:
        return None
    try:
        return date.fromisoformat(raw[:10])
    except ValueError as exc:
        raise ValueError(f"invalid source graph date: {raw}") from exc


__all__ = [
    "SOURCE_FAMILY_CLASSES",
    "SourceGraphEdge",
    "SourceGraphExploration",
    "SourceGraphExplorer",
    "SourceGraphNode",
    "SourceResearchObjective",
]
